### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by DarwinNE** [simon-zz/fidocadj-debian-package-builder#3]
Hi to all,
  I was having a look at the file:

[https://github.com/simon-zz/fidocadj-debian-package-builder/blob/master/deb/DEBIAN/control
](https://github.com/simon-zz/fidocadj-debian-package-builder/blob/master/deb/DEBIAN/control)

The description right now is
`Description: 2D CAD for electrical and electronics schematics developed by Davide Bucci
   FidocadJ is a 2D CAD for electrical and electronics schematics developed by Davide Bucci. This is a test.`

I propose something like "FidoCadJ is a free user-friendly vector graphic editor for MacOSX, Linux, Windows and Android" without referring to myself, since I am not the only one working on the code :)

Maybe a phrase such as "FidoCadJ is particularly convenient for editing electronics schematics diagrams and simple PCB's thanks to a comprehensive library of symbols."

The correct spelling of FidoCadJ has the "F", "C" and "J" capital.

Cheers,
D.

**Comment by gveezz** [comment]
Hi Davide. 

Keep in mind that the first line is a brief description.
The second one should be a complete description.

I let you decide what we can write on both lines and I will merge the changes. :)
Regards,
Simon

**Comment by DarwinNE** [comment]
Hi @simon-zz 
So, here is what I would write:
First line: 

> FidoCadJ is a simple graphic editor with a collection of symbols for electronic circuits.

Complete description:

> FidoCadJ is a free user-friendly vector graphic editor which runs on MacOSX, Linux, Windows and Android. It is very easy to use and it can export drawings in a variety of graphic formats. FidoCadJ stores the drawings in a very simple  text-only file format which can be easily copy/pasted in forums and newsgroup. Libraries containing a huge variety of symbols for electronics are available and you can create your own.

If you spot some typos or you think that the description should be improved, feel free to do it.

Cheers and thanks again,

D.

**Comment by gveezz** [comment]
Hi Davide,
I updated the description. +1: 
Regards,
Simon
